// Code generated by goctl. DO NOT EDIT.
package types

type AddReq struct {
	Article string `form:"article"`
}

type AddResp struct {
	Ok bool `json:"ok"`
}

type CheckReq struct {
	Article string `form:"article"`
}

type CheckResp struct {
	Found bool `json:"found"`
}
