#!/usr/bin/env python3
# 第一行注释可以直接在Unix/Linux/Mac
# -*- coding: utf-8 -*-
# 使用标准UTF-8编码

""" a test module """

__author__ = 'kai wang'

import sys


def test():
    args = sys.argv
    if len(args) == 1:
        print('Hello, world!')
    elif len(args) == 2:
        print('Hello, %s!' % args[1])
    else:
        print('Too many arguments!')


if __name__ == '__main__':
    test()


def lazy_sum(*args):
    def sum():
        ax = 0
        for n in args:
            ax = ax + n
        return ax
    return sum

def count():
    fs = []
    for i in range(1, 4):
        def f():
            return i*i
        fs.append(f)
    return fs


f = lambda x: x*1


def build(x, y):
    return lambda: x*x+y*y


def now():
    print('2015-3-25')


def log(func):
    def wrapper(*args,**kw):
        print('call %s()' % func.__name__)
        return func(*args, **kw)
    return wrapper


@log
def now():
    print('2015-3-25')


now()


def intpass(x, base=2):
    return int(x, base)


a = intpass('1000000')
print(a)


