apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-labeler
  namespace: default
rules:
- apiGroups: [""] # "" 表示核心API组
  resources: ["pods"]
  verbs: ["get", "list", "patch"] # "patch" 是给资源打标签所需的权限
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-labeler-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default # 绑定到 "default" 服务账号
  namespace: default
roleRef:
  kind: Role
  name: pod-labeler
  apiGroup: rbac.authorization.k8s.io
