#!/user/bin/env python3
# -*- coding: utf-8 -*-
from urllib.request import urlopen
from bs4 import BeautifulSoup
from pyquery import PyQuery as qp


html = urlopen('http://www.pythonscraping.com/pages/page1.html')
html = html.read().decode("utf-8")
bsobj = qp(url='http://www.pythonscraping.com/pages/page1.html')
print(bsobj('h1'))

