apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubemin-cli.fullname" . }}
  labels:
    {{- include "kubemin-cli.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: apiserver
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubemin-cli.fullname" . }}
  labels:
    {{- include "kubemin-cli.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: apiserver
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "kubemin-cli.labels" . | nindent 8 }}
        app.kubernetes.io/component: apiserver
    spec:
      containers:
        - name: kubemin-cli
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: MYSQL_HOST
              value: {{ include "kubemin-cli.fullname" . }}-mysql
            - name: MYSQL_PORT
              value: "{{ .Values.mysql.servicePort }}"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kubemin-cli.fullname" . }}-mysql
                  key: password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: REDIS_ADDR
              value: {{ include "kubemin-cli.fullname" . }}-redis:{{ .Values.redis.servicePort }}
            {{- if .Values.env }}
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
