apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubemin-cli.fullname" . }}-mysql
  labels:
    {{- include "kubemin-cli.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: {{ .Values.mysql.servicePort }}
      targetPort: mysql
  selector:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kubemin-cli.fullname" . }}-mysql
  labels:
    {{- include "kubemin-cli.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kubemin-cli.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mysql
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "kubemin-cli.labels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: {{ .Values.mysql.servicePort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kubemin-cli.fullname" . }}-mysql
                  key: password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mysql.storage }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubemin-cli.fullname" . }}-mysql
  labels:
    {{- include "kubemin-cli.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.mysql.rootPassword | b64enc }}
