// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	Id                   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	No                   int32          `protobuf:"varint,2,opt,name=no,proto3" json:"no,omitempty"`
	FirstName            string         `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string         `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	MonthSalay           *MonthSalary   `protobuf:"bytes,6,opt,name=monthSalay,proto3" json:"monthSalay,omitempty"`
	Status               EmployeeStatus `protobuf:"varint,7,opt,name=status,proto3,enum=EmployeeStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Employee) GetNo() int32 {
	if m != nil {
		return m.No
	}
	return 0
}

func (m *Employee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Employee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Employee) GetMonthSalay() *MonthSalary {
	if m != nil {
		return m.MonthSalay
	}
	return nil
}

func (m *Employee) GetStatus() EmployeeStatus {
	if m != nil {
		return m.Status
	}
	return EmployeeStatus_NORMAL
}

type MonthSalary struct {
	Basic                float32  `protobuf:"fixed32,1,opt,name=basic,proto3" json:"basic,omitempty"`
	Bonus                float32  `protobuf:"fixed32,2,opt,name=bonus,proto3" json:"bonus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonthSalary) Reset()         { *m = MonthSalary{} }
func (m *MonthSalary) String() string { return proto.CompactTextString(m) }
func (*MonthSalary) ProtoMessage()    {}
func (*MonthSalary) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *MonthSalary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonthSalary.Unmarshal(m, b)
}
func (m *MonthSalary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonthSalary.Marshal(b, m, deterministic)
}
func (m *MonthSalary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonthSalary.Merge(m, src)
}
func (m *MonthSalary) XXX_Size() int {
	return xxx_messageInfo_MonthSalary.Size(m)
}
func (m *MonthSalary) XXX_DiscardUnknown() {
	xxx_messageInfo_MonthSalary.DiscardUnknown(m)
}

var xxx_messageInfo_MonthSalary proto.InternalMessageInfo

func (m *MonthSalary) GetBasic() float32 {
	if m != nil {
		return m.Basic
	}
	return 0
}

func (m *MonthSalary) GetBonus() float32 {
	if m != nil {
		return m.Bonus
	}
	return 0
}

type GetByNoRequest struct {
	No                   int32    `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByNoRequest) Reset()         { *m = GetByNoRequest{} }
func (m *GetByNoRequest) String() string { return proto.CompactTextString(m) }
func (*GetByNoRequest) ProtoMessage()    {}
func (*GetByNoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *GetByNoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByNoRequest.Unmarshal(m, b)
}
func (m *GetByNoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByNoRequest.Marshal(b, m, deterministic)
}
func (m *GetByNoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByNoRequest.Merge(m, src)
}
func (m *GetByNoRequest) XXX_Size() int {
	return xxx_messageInfo_GetByNoRequest.Size(m)
}
func (m *GetByNoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByNoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByNoRequest proto.InternalMessageInfo

func (m *GetByNoRequest) GetNo() int32 {
	if m != nil {
		return m.No
	}
	return 0
}

type EmployeeResponse struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeResponse) Reset()         { *m = EmployeeResponse{} }
func (m *EmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeeResponse) ProtoMessage()    {}
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *EmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeResponse.Unmarshal(m, b)
}
func (m *EmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeResponse.Marshal(b, m, deterministic)
}
func (m *EmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeResponse.Merge(m, src)
}
func (m *EmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeeResponse.Size(m)
}
func (m *EmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeResponse proto.InternalMessageInfo

func (m *EmployeeResponse) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type AddPhotoRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPhotoRequest) Reset()         { *m = AddPhotoRequest{} }
func (m *AddPhotoRequest) String() string { return proto.CompactTextString(m) }
func (*AddPhotoRequest) ProtoMessage()    {}
func (*AddPhotoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *AddPhotoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPhotoRequest.Unmarshal(m, b)
}
func (m *AddPhotoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPhotoRequest.Marshal(b, m, deterministic)
}
func (m *AddPhotoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPhotoRequest.Merge(m, src)
}
func (m *AddPhotoRequest) XXX_Size() int {
	return xxx_messageInfo_AddPhotoRequest.Size(m)
}
func (m *AddPhotoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPhotoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPhotoRequest proto.InternalMessageInfo

func (m *AddPhotoRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddPhotoResponse struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPhotoResponse) Reset()         { *m = AddPhotoResponse{} }
func (m *AddPhotoResponse) String() string { return proto.CompactTextString(m) }
func (*AddPhotoResponse) ProtoMessage()    {}
func (*AddPhotoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *AddPhotoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPhotoResponse.Unmarshal(m, b)
}
func (m *AddPhotoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPhotoResponse.Marshal(b, m, deterministic)
}
func (m *AddPhotoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPhotoResponse.Merge(m, src)
}
func (m *AddPhotoResponse) XXX_Size() int {
	return xxx_messageInfo_AddPhotoResponse.Size(m)
}
func (m *AddPhotoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPhotoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPhotoResponse proto.InternalMessageInfo

func (m *AddPhotoResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type EmployeeRequest struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeRequest) Reset()         { *m = EmployeeRequest{} }
func (m *EmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeeRequest) ProtoMessage()    {}
func (*EmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}

func (m *EmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeRequest.Unmarshal(m, b)
}
func (m *EmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeRequest.Marshal(b, m, deterministic)
}
func (m *EmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeRequest.Merge(m, src)
}
func (m *EmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeeRequest.Size(m)
}
func (m *EmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeRequest proto.InternalMessageInfo

func (m *EmployeeRequest) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

func init() {
	proto.RegisterType((*Employee)(nil), "Employee")
	proto.RegisterType((*MonthSalary)(nil), "MonthSalary")
	proto.RegisterType((*GetByNoRequest)(nil), "GetByNoRequest")
	proto.RegisterType((*EmployeeResponse)(nil), "EmployeeResponse")
	proto.RegisterType((*GetAllRequest)(nil), "GetAllRequest")
	proto.RegisterType((*AddPhotoRequest)(nil), "AddPhotoRequest")
	proto.RegisterType((*AddPhotoResponse)(nil), "AddPhotoResponse")
	proto.RegisterType((*EmployeeRequest)(nil), "EmployeeRequest")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x41, 0x6b, 0xdb, 0x30,
	0x18, 0x45, 0x9e, 0xe3, 0x38, 0x5f, 0x3a, 0xdb, 0x15, 0x1b, 0x98, 0xd0, 0x83, 0x31, 0x74, 0x33,
	0x6c, 0x15, 0x9d, 0x77, 0x59, 0x8f, 0x2d, 0x8c, 0xc0, 0x60, 0x5d, 0x51, 0x0e, 0x83, 0xdd, 0x94,
	0xf8, 0xdb, 0x6a, 0x66, 0x5b, 0x9e, 0xa5, 0x14, 0x72, 0xde, 0xbf, 0xd9, 0x3f, 0xd9, 0xbf, 0x1a,
	0x56, 0xe4, 0xa4, 0xcd, 0x7a, 0xe8, 0x4d, 0xef, 0x7d, 0x4f, 0x9f, 0xde, 0x7b, 0x20, 0x08, 0x6a,
	0x54, 0x4a, 0xfc, 0x40, 0xc5, 0xda, 0x4e, 0x6a, 0x39, 0x9b, 0x62, 0xb3, 0xae, 0x2d, 0x48, 0xff,
	0x12, 0xf0, 0x3f, 0xd6, 0x6d, 0x25, 0x37, 0x88, 0x34, 0x00, 0xa7, 0x2c, 0x62, 0x92, 0x90, 0x6c,
	0xc4, 0x9d, 0xb2, 0xe8, 0x71, 0x23, 0x63, 0x67, 0x8b, 0x1b, 0x49, 0x4f, 0x60, 0xf2, 0xbd, 0xec,
	0x94, 0xbe, 0x16, 0x35, 0xc6, 0xcf, 0x12, 0x92, 0x4d, 0xf8, 0x9e, 0xa0, 0x33, 0xf0, 0x2b, 0x61,
	0x87, 0xae, 0x19, 0xee, 0x30, 0x7d, 0x0b, 0x50, 0xcb, 0x46, 0xdf, 0x2e, 0x44, 0x25, 0x36, 0xb1,
	0x97, 0x90, 0x6c, 0x9a, 0x1f, 0xb1, 0xcf, 0x03, 0xd5, 0x6d, 0xf8, 0xbd, 0x39, 0x7d, 0x0d, 0x9e,
	0xd2, 0x42, 0xaf, 0x55, 0x3c, 0x4e, 0x48, 0x16, 0xe4, 0x21, 0x1b, 0x2c, 0x2e, 0x0c, 0xcd, 0xed,
	0xf8, 0x93, 0xeb, 0x8f, 0x22, 0x8f, 0x7b, 0xca, 0xac, 0x48, 0x2f, 0x60, 0x7a, 0x6f, 0x23, 0x7d,
	0x01, 0xa3, 0xa5, 0x50, 0xe5, 0xca, 0x04, 0x72, 0xf8, 0x16, 0x18, 0x56, 0x36, 0x6b, 0x65, 0x62,
	0xf5, 0x6c, 0x0f, 0xd2, 0x04, 0x82, 0x39, 0xea, 0xab, 0xcd, 0xb5, 0xe4, 0xf8, 0x6b, 0x8d, 0x4a,
	0xdb, 0xec, 0x64, 0xc8, 0x9e, 0x5e, 0x40, 0x34, 0x98, 0xe0, 0xa8, 0x5a, 0xd9, 0x28, 0xa4, 0xa7,
	0xe0, 0xa3, 0xe5, 0x8c, 0x72, 0x9a, 0x4f, 0x76, 0x4e, 0xf9, 0x6e, 0x94, 0x86, 0xf0, 0x7c, 0x8e,
	0xfa, 0xb2, 0xaa, 0xec, 0xee, 0xf4, 0x14, 0xc2, 0xcb, 0xa2, 0xb8, 0xb9, 0x95, 0x7a, 0xf7, 0x1c,
	0x05, 0xb7, 0x10, 0x5a, 0x98, 0x35, 0x47, 0xdc, 0x9c, 0xd3, 0x57, 0x10, 0xed, 0x65, 0xf6, 0x49,
	0x0a, 0x6e, 0xa9, 0xbe, 0xfc, 0x34, 0x3a, 0x9f, 0x9b, 0x73, 0xfa, 0x01, 0xc2, 0xbd, 0xb5, 0xed,
	0xba, 0xa7, 0x39, 0xcb, 0x7f, 0x3b, 0xfb, 0xab, 0x0b, 0xec, 0xee, 0xca, 0x15, 0xd2, 0x33, 0x18,
	0xdb, 0x2a, 0x68, 0xc8, 0x1e, 0x96, 0x32, 0x3b, 0x66, 0xff, 0x75, 0x70, 0x06, 0xde, 0x36, 0x1c,
	0x0d, 0xd8, 0x83, 0x94, 0x8f, 0x88, 0xcf, 0x09, 0x7d, 0x07, 0xfe, 0x90, 0x89, 0x46, 0xec, 0xa0,
	0x85, 0xd9, 0x31, 0x3b, 0x0c, 0x9c, 0x11, 0xfa, 0x06, 0xdc, 0x85, 0xb8, 0x43, 0x1a, 0xb1, 0x83,
	0x94, 0x8f, 0xd9, 0xc9, 0x61, 0xdc, 0x8b, 0x7b, 0x3f, 0x4f, 0xd1, 0x67, 0xe4, 0x9c, 0x5c, 0x9d,
	0x7c, 0x73, 0xda, 0xe5, 0x1f, 0xe7, 0xe5, 0xbc, 0x6b, 0x57, 0x7d, 0x0b, 0xd8, 0xb1, 0xaf, 0xb8,
	0x64, 0x37, 0xfd, 0x07, 0x51, 0x4b, 0xcf, 0x7c, 0x94, 0xf7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x90, 0x92, 0x7f, 0xd8, 0x47, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	GetByNo(ctx context.Context, in *GetByNoRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (EmployeeService_GetAllClient, error)
	AddPhoto(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_AddPhotoClient, error)
	Save(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	SaveAll(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_SaveAllClient, error)
}

type employeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeServiceClient(cc grpc.ClientConnInterface) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetByNo(ctx context.Context, in *GetByNoRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/EmployeeService/GetByNo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (EmployeeService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeService_serviceDesc.Streams[0], "/EmployeeService/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EmployeeService_GetAllClient interface {
	Recv() (*EmployeeResponse, error)
	grpc.ClientStream
}

type employeeServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *employeeServiceGetAllClient) Recv() (*EmployeeResponse, error) {
	m := new(EmployeeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeeServiceClient) AddPhoto(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_AddPhotoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeService_serviceDesc.Streams[1], "/EmployeeService/AddPhoto", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceAddPhotoClient{stream}
	return x, nil
}

type EmployeeService_AddPhotoClient interface {
	Send(*AddPhotoRequest) error
	CloseAndRecv() (*AddPhotoResponse, error)
	grpc.ClientStream
}

type employeeServiceAddPhotoClient struct {
	grpc.ClientStream
}

func (x *employeeServiceAddPhotoClient) Send(m *AddPhotoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *employeeServiceAddPhotoClient) CloseAndRecv() (*AddPhotoResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddPhotoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeeServiceClient) Save(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/EmployeeService/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) SaveAll(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_SaveAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeService_serviceDesc.Streams[2], "/EmployeeService/SaveAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceSaveAllClient{stream}
	return x, nil
}

type EmployeeService_SaveAllClient interface {
	Send(*EmployeeRequest) error
	Recv() (*EmployeeResponse, error)
	grpc.ClientStream
}

type employeeServiceSaveAllClient struct {
	grpc.ClientStream
}

func (x *employeeServiceSaveAllClient) Send(m *EmployeeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *employeeServiceSaveAllClient) Recv() (*EmployeeResponse, error) {
	m := new(EmployeeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	GetByNo(context.Context, *GetByNoRequest) (*EmployeeResponse, error)
	GetAll(*GetAllRequest, EmployeeService_GetAllServer) error
	AddPhoto(EmployeeService_AddPhotoServer) error
	Save(context.Context, *EmployeeRequest) (*EmployeeResponse, error)
	SaveAll(EmployeeService_SaveAllServer) error
}

// UnimplementedEmployeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (*UnimplementedEmployeeServiceServer) GetByNo(ctx context.Context, req *GetByNoRequest) (*EmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByNo not implemented")
}
func (*UnimplementedEmployeeServiceServer) GetAll(req *GetAllRequest, srv EmployeeService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedEmployeeServiceServer) AddPhoto(srv EmployeeService_AddPhotoServer) error {
	return status.Errorf(codes.Unimplemented, "method AddPhoto not implemented")
}
func (*UnimplementedEmployeeServiceServer) Save(ctx context.Context, req *EmployeeRequest) (*EmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (*UnimplementedEmployeeServiceServer) SaveAll(srv EmployeeService_SaveAllServer) error {
	return status.Errorf(codes.Unimplemented, "method SaveAll not implemented")
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_GetByNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetByNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmployeeService/GetByNo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetByNo(ctx, req.(*GetByNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmployeeServiceServer).GetAll(m, &employeeServiceGetAllServer{stream})
}

type EmployeeService_GetAllServer interface {
	Send(*EmployeeResponse) error
	grpc.ServerStream
}

type employeeServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *employeeServiceGetAllServer) Send(m *EmployeeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EmployeeService_AddPhoto_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServiceServer).AddPhoto(&employeeServiceAddPhotoServer{stream})
}

type EmployeeService_AddPhotoServer interface {
	SendAndClose(*AddPhotoResponse) error
	Recv() (*AddPhotoRequest, error)
	grpc.ServerStream
}

type employeeServiceAddPhotoServer struct {
	grpc.ServerStream
}

func (x *employeeServiceAddPhotoServer) SendAndClose(m *AddPhotoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *employeeServiceAddPhotoServer) Recv() (*AddPhotoRequest, error) {
	m := new(AddPhotoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _EmployeeService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmployeeService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).Save(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_SaveAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServiceServer).SaveAll(&employeeServiceSaveAllServer{stream})
}

type EmployeeService_SaveAllServer interface {
	Send(*EmployeeResponse) error
	Recv() (*EmployeeRequest, error)
	grpc.ServerStream
}

type employeeServiceSaveAllServer struct {
	grpc.ServerStream
}

func (x *employeeServiceSaveAllServer) Send(m *EmployeeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *employeeServiceSaveAllServer) Recv() (*EmployeeRequest, error) {
	m := new(EmployeeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByNo",
			Handler:    _EmployeeService_GetByNo_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _EmployeeService_Save_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _EmployeeService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddPhoto",
			Handler:       _EmployeeService_AddPhoto_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SaveAll",
			Handler:       _EmployeeService_SaveAll_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "messages.proto",
}
