// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"KubeMin-Cli/pkg/examples/demo/handler"
	"KubeMin-Cli/pkg/examples/demo/ioc"
	"KubeMin-Cli/pkg/examples/demo/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp() *gin.Engine {
	iApplications := service.NewApplicationService()
	applicationHandler := handler.NewApplicationHandler(iApplications)
	engine := ioc.NewGinEngineAndRegisterRoute(applicationHandler)
	return engine
}
