version: '3.8'

services:
  # Redis服务（用于分布式工作流队列）
  redis:
    image: redis:7-alpine
    container_name: kubemin-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - kubemin-network

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: kubemin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: kubemin_cli
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kubemin-network

  # Jaeger追踪服务（可选）
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: kubemin-jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - kubemin-network

  # KubeMin-Cli节点1（Leader候选）
  kubemin-node1:
    build:
      context: ../..
      dockerfile: deploy/distributed/Dockerfile
    container_name: kubemin-node1
    environment:
      - REDIS_ADDR=redis:6379
      - MYSQL_ADDR=mysql:3306
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - NODE_ID=node1
    ports:
      - "8001:8008"
    depends_on:
      - redis
      - mysql
      - jaeger
    volumes:
      - ./config.yaml:/app/config.yaml
      - ~/.kube/config:/root/.kube/config:ro
    command: [
      "/app/kubemin-cli",
      "--redis-addr=redis:6379",
      "--enable-distributed=true",
      "--max-workers=5",
      "--id=node1"
    ]
    networks:
      - kubemin-network

  # KubeMin-Cli节点2（Leader候选）
  kubemin-node2:
    build:
      context: ../..
      dockerfile: deploy/distributed/Dockerfile
    container_name: kubemin-node2
    environment:
      - REDIS_ADDR=redis:6379
      - MYSQL_ADDR=mysql:3306
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - NODE_ID=node2
    ports:
      - "8002:8008"
    depends_on:
      - redis
      - mysql
      - jaeger
    volumes:
      - ./config.yaml:/app/config.yaml
      - ~/.kube/config:/root/.kube/config:ro
    command: [
      "/app/kubemin-cli",
      "--redis-addr=redis:6379",
      "--enable-distributed=true",
      "--max-workers=5",
      "--id=node2"
    ]
    networks:
      - kubemin-network

  # KubeMin-Cli节点3（Worker专用）
  kubemin-worker:
    build:
      context: ../..
      dockerfile: deploy/distributed/Dockerfile
    container_name: kubemin-worker
    environment:
      - REDIS_ADDR=redis:6379
      - MYSQL_ADDR=mysql:3306
      - NODE_ID=worker1
    depends_on:
      - redis
      - mysql
    volumes:
      - ./config.yaml:/app/config.yaml
      - ~/.kube/config:/root/.kube/config:ro
    command: [
      "/app/kubemin-cli",
      "--redis-addr=redis:6379",
      "--enable-distributed=true",
      "--max-workers=10",
      "--id=worker1"
    ]
    networks:
      - kubemin-network

networks:
  kubemin-network:
    driver: bridge

volumes:
  redis-data:
  mysql-data: